[2025-02-13T10:25:01.784+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.create_table scheduled__2024-07-17T00:00:00+00:00 [queued]>
[2025-02-13T10:25:01.791+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.create_table scheduled__2024-07-17T00:00:00+00:00 [queued]>
[2025-02-13T10:25:01.792+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-02-13T10:25:01.803+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table> on 2024-07-17 00:00:00+00:00
[2025-02-13T10:25:01.809+0000] {standard_task_runner.py:60} INFO - Started process 138 to run task
[2025-02-13T10:25:01.811+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'create_table', 'scheduled__2024-07-17T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpmg3zt7or']
[2025-02-13T10:25:01.812+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask create_table
[2025-02-13T10:25:01.846+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_and_store_amazon_books.create_table scheduled__2024-07-17T00:00:00+00:00 [running]> on host 7500ade24691
[2025-02-13T10:25:01.893+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-17T00:00:00+00:00'
[2025-02-13T10:25:01.894+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS books (
            id SERIAL PRIMARY KEY,
            title TEXT NOT NULL,
            authors TEXT,
            price TEXT,
            rating TEXT
        );
        
[2025-02-13T10:25:01.900+0000] {base.py:83} INFO - Using connection ID 'books_connection' for task execution.
[2025-02-13T10:25:01.907+0000] {base.py:83} INFO - Using connection ID 'books_connection' for task execution.
[2025-02-13T10:25:01.908+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.18.0.2", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-02-13T10:25:01.914+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fetch_and_store_amazon_books, task_id=create_table, execution_date=20240717T000000, start_date=20250213T102501, end_date=20250213T102501
[2025-02-13T10:25:01.920+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task create_table (connection to server at "172.18.0.2", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 138)
[2025-02-13T10:25:01.950+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-13T10:25:01.966+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
